apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: face-swap
    tier: backend
    deployedBy: deploy-node-app
  name: face-swap
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: face-swap
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: face-swap
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: jefftian/face-swap:latest
          imagePullPolicy: Always
          name: face-swap
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          envFrom: []
          readinessProbe:
            httpGet:
              port: 5000
              path: /
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
