apiVersion: v1
kind: Service
metadata:
  name: face-swap
  annotations:
    dev.okteto.com/auto-ingress: 'true'
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: face-swap
    tier: backend

