# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cicd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 */12 * * *'

jobs:

  deploy-napptive:
    name: Deploy to napptive
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: napptive-actions/playground-github-action@v4.1.0
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        with:
          cmd: "apps deploy face-swap.yaml"

  update-napptive:
    name: update napptive
    if: ${{ always() }}
    needs: deploy-napptive
    runs-on: ubuntu-latest
    env:
      PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "Downloading NAPPTIVE Playground CLI"
      - run: curl -O https://storage.googleapis.com/artifacts.playground.napptive.dev/installer.sh && bash installer.sh

      - run: echo "Downloading Kubectl"
      - run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - run: chmod +x kubectl
      - run: echo "Login into NAPPTIVE Playground"
      - run: playground login --pat
      - run: playground get-kubeconfig
      - run: ls ~/.napptive/default/napptive-kubeconfig

      - name: update
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        run: |
          export PATH=$PATH:$(pwd)
          echo "Forcing rolling update to download newest image"
          export IMAGE="jefftian/face-swap:latest"
          echo "Update image... ${IMAGE}"
          export PATCH='{"spec":{"workload":{"spec":{"containers":\ [{"name":"face-swap", "image":"${IMAGE}"}]}}}}'
          echo "patch = ${PATCH}"
          kubectl --kubeconfig ~/.napptive/default/napptive-kubeconfig patch deploy face-swap --patch '{"spec":{"template":{"spec":{"containers":[{"image":"jefftian/face-swap","name":"face-swap"}]}}}}' --type=merge

  deploy-okteto:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - run: chmod +x ./kubectl
      - run: sudo mv ./kubectl /usr/local/bin/kubectl
      - run: mkdir ${HOME}/.kube
      - run: npm i -g k8ss
      - run: echo -e "machine github.com\n  login ${{secrets.GH_TOKEN}}" > ~/.netrc
      - run: git clone https://github.com/Jeff-Tian/k8s-config.git ${HOME}/k8s-config
      - run: k8ss switch --cluster=okteto --namespace=jeff-tian&&kubectl rollout restart deploy face-swap

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - run: sh .travis/ci.sh